# Generated by Django 2.1.5 on 2019-01-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_as_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=50)),
                ('order_id', models.IntegerField(max_length=30, null=True)),
                ('tariff', models.CharField(max_length=10)),
                ('status', models.CharField(default='Ищем водителей', max_length=10)),
                ('bort', models.CharField(max_length=50)),
            ],
        ),
    ]
