# Generated by Django 2.1.5 on 2019-01-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bort',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Ищем водителей', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tariff',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
