# Generated by Django 2.1.5 on 2019-01-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190111_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bort',
            field=models.CharField(max_length=50),
        ),
    ]
